### ISSUE TITLE
Forge 1.7.2 currently not available

### ISSUE THREAD

**Issue by fktc** [metadaddy/Forcecraft#15]
As of October 2021, there is currently [no working installer for Forge 1.7.2](https://forums.minecraftforge.net/announcement/13-old-installers-currently-do-not-work/). Forge is available for Version 1.6.4, but it crashes on launch with Forcecraft 0.2.3 installed.

What is the recommended way to run Forcecraft today on MacOS Big Sur? Is there a legacy Forcecraft jar available that works with 1.6.4?

**Comment by metadaddy** [comment]
Hi @fktc - your best bet is to try the 1.7.10-10.13.4.1614-1.7.10 installer mentioned at that announcement. 1.7.x versions will be much closer than 1.6.x and 1.7.x. Good luck, and let me know how it goes!

**Comment by metadaddy** [comment]
@fktc reports out of band that the `1.7.10-10.13.4.1614-1.7.10` installer mentioned at https://forums.minecraftforge.net/announcement/13-old-installers-currently-do-not-work/ launches Forcecraft successfully.

**Comment by fktc** [comment]
Confirmed, 1.7.10-10.13.4.1614-1.7.10 works with Forcecraft on Big Sur & java 17 2021-09-14 LTS. No issues or bugs detected. Thanks for your help @metadaddy .
